### ISSUE TITLE
Layer Variants

### ISSUE THREAD

**Issue by ColinMulcahy** [bitfocus/companion-module-boinx-mimolive#1]
Hi,

I can call layers with "document index, layer index". How do you call layer variants?

**Comment by sphlabs** [comment]
Directly addressing layer variants is on the roadmap to add. Currently, there is no index provided for variants, so `document index, layer index, variant index` wouldn’t work — only via a specific endpoint for each variant.

How useful would it be for you to have the ability to call variants by index?

**Comment by ColinMulcahy** [comment]
> Directly addressing layer variants is on the roadmap to add. Currently, there is no index provided for variants, so `document index, layer index, variant index` wouldn’t work — only via a specific endpoint for each variant.
> 
> How useful would it be for you to have the ability to call variants by index?

It would be 100% useful. It would complelety change our workflow and make our productions seamless with interactions with ATEM.

1). If I understand correctly, having variant index means no hardwiring of endpoint id's and dependancy on document Id etc.
2). I could have 30 variants on one layer, indexing would remove the worry of human error of cutting and pasting endpoints.
2). The ability to edit layer variants in MimoLive and have them auto update in Companion makes one point of entry.

As it stands presently without layer variants, using companion is very limited to the point where operational flow remains  within MimoLive. In otherwords, we just don't use the companion module in our workflow. But with variant indexing it would completely change our workflow and reduce the complexity of graphic manipulation on our productions.

Thanks for all the work you are doing.

**Comment by sphlabs** [comment]
That's really good feedback, thank you.

I have discussed with Boinx adding variant (and source, output) indexes to the API. They are open to this, although it won't likely be for a little while due to the other priorities they are working on at the moment.

**Comment by sphlabs** [comment]
The latest beta version of Companion now has variant support.

This is currently limited to API Endpoint addressing only, as index addressing will require an API change by Boinx first.
