### ISSUE TITLE
Bug: pollApi is not cleaned up

### ISSUE THREAD

**Issue by Julusian** [bitfocus/companion-module-boinx-mimolive#3]
An interval is created https://github.com/bitfocus/companion-module-boinx-mimolive/blob/main/src/api.js#L267 when setting up the connection. 
This interval does not appear to be cleaned up at any point, so if the module is disabled or reconfigured it will be left running.

Additionally, should https://github.com/bitfocus/companion-module-boinx-mimolive/blob/main/src/index.js#L155 be `initAPI`? I dont see an implementation for `initTCP` anywhere

**Comment by sphlabs** [comment]
These bugs should be resolved now.
